inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*' 
    - 'config/**/*'

Layout/LineLength:
  Max: 120 

Lint/ShadowingOuterLocalVariable:
  Enabled: false 

Metrics/AbcSize: 
  Max: 30 

Metrics/BlockLength: 
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength: 
  Max: 40 

Metrics/PerceivedComplexity: 
  Max: 10 

Metrics/AbcSize:
  Max: 35 

Style/CaseEquality:
  Enabled: false 

Style/ClassAndModuleChildren:
  Enabled: false 

Style/Documentation:
  Enabled: false 

Style/FrozenStringLiteralComment: 
  Enabled: false 

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false 

Style/RedundantFetchBlock:
  Enabled: false 