version: '3' 

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - articles-network
      
  app:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /articles_app/config/unicorn.conf.rb
    tty: true
    stdin_open: true 
    volumes:
      - .:/articles_app:cached
      - public:/articles_app/public 
      - tmp-data:/articles_app/tmp/sockets
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - articles-network
    env_file:
      - ./.env

  web:
    build:
      context: containers/nginx 
      dockerfile: Dockerfile
    volumes:
      - public:/articles_app/public 
      - tmp-data:/articles_app/tmp/sockets
    ports: 
      - 80:80 
    depends_on:
      - app
    networks:
      - articles-network

volumes:
  mysql_data:
  public:
  tmp-data:

networks:
  articles-network:
    external: true