services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.32
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      articles-net:

  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000 
    depends_on:
      - db
      - chrome
    volumes:
      - .:/articles_app/  
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    env_file:
      - ./.env
    networks:
      articles-net:

  chrome:
    # platform: linux/x86_64
    image: seleniarm/standalone-chromium
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=2
    ports:
      - 4444:4444
    networks:
      articles-net:

networks:
  articles-net:
    external: true

volumes:
  mysql_data: