version: '3' 

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
      
  app:
    build: 
      context: . 
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /articles_app/config/unicorn.conf.rb
    tty: true
    stdin_open: true 
    volumes:
      - .:/articles_app/
      - public:/articles_app/public 
    ports:
      - 3000:3000
    depends_on:
      - db

  web:
    build:
      context: containers/nginx 
      dockerfile: Dockerfile
    volumes:
      - public:/articles_app/public 
    ports: 
      - 80:80 
    depends_on:
      - app

volumes:
  mysql_data:
  public: