version: '3' 

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
      
  app:
    build: .
    command: bundle exec unicorn_rails -p 3000 -c config/unicorn.rb -E production -D
    tty: true
    stdin_open: true 
    volumes:
      - .:/articles_app/
      - public:/articles_app/public 
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - RAILS_ENV=production 

  web:
    build:
      context: containers/nginx 
    volumes:
      - public:/articles_app/public 
    ports: 
      - 80:80 

volumes:
  mysql_data:
  public: