version: '3' 

services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_USER: user 
      MYSQL_ROOT_PASSWORD: pass 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
      
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/articles_app/
    ports:
      - "3000:3000"
    depends_on: 
      - db 

volumes:
  mysql_data: