version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/articles_app
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose -f docker-compose-dev.yml up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose -f docker-compose-dev.yml stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose -f docker-compose-dev.yml up -d
